const products = [
    {
        title:"Papas fritas" ,
        precio:400 ,
        stock:3 ,
        id: 1,
        imagen:'papas imagen ppal.jpg',
        image:'papas con cheddarotra.png',
        image1:'papas con cheddar zoom.png',
        image2:'verdeo.png',
        image3:'panceta.png',
        image4:'cheddar2.jpg',
        

    },
       {
        title:"Hamburguesa completa",
         stock:3 ,
         precio:650 ,
         id: 2,
         imagen:'hamburguesa ppal.png',
         image:'hamburguesa.png',
        image1:'zoom hamburguesa.png',
        image2:'cebolla caramelizada.png',
        image3:'salsa cheddar.png',
        image4:'panceta.png',
        
    },
        {
        title:"Ingredientes adicionales" ,
        stock:40 , 
        precio:80 ,
        id: 3,
        imagen:'ingredientes extra ppal.png',
        image:'guacamole.png',
        image1:'chile.png',
        image2:'jamon.png',
        image3:'palmitos.png',
        image4:'aceitunas.png',
    },
    {
        title:"Ensalada mixta" ,
        precio:400 ,
        stock:4 ,
        id: 4,
        imagen:'ensalada ppal.png',
        image:'zoom ensalada.png',
        image1:'pollo.png',
        image2:'lechuga.png',
        image3:'queso.png',
        image4:'dados.png',
    },
    {
        title:"Sanguche de bondiola" ,
        stock:4  ,
        precio:800 ,
        id: 5,
        imagen:'bondiola ppal.png',
        image:'bondiola zoom.png',
        image1:'bondiola.png',
        image2:'huevo frito.png',
        image3:'panceta.png',
        image4:'salsa cheddar.png',
    } 
]
export default products