const products = [
    {
        title:"Papas fritas" ,
        precio:400 ,
        stock:3 ,
        id: 1,
        imagen:'papas imagen ppal.jpg',
        image:'papas con cheddarotra.png',
        image1:'papas con cheddar zoom.png',
        image2:'verdeo.png',
        image3:'panceta.png',
        image4:'cheddar2.jpg',
        

    },
       {
        title:"Hamburguesa completa",
         stock:3 ,
         precio:650 ,
         id: 2,
         imagen:'hamburguesa.jpg',
         image:'papas con cheddarotra.png',
        image1:'papas con chedar zoom.png',
        image2:'papas con chedar zoom.png',
        image3:'papas con chedar zoom.png',
        image4:'papas con chedar zoom.png',
        
    },
        {
        title:"Ingredientes adicionales" ,
        stock:40 , 
        precio:80 ,
        id: 3,
        imagen:'ingredientes.jpg',
        image:'papas con cheddarotra.png',
        image1:'papas con chedarotra.png',
        image2:'verdeo.png',
        image3:'panceta.png',
        image4:'cheddar2.png',
    },
    {
        title:"Ensalada mixta" ,
        precio:400 ,
        stock:4 ,
        id: 4,
        imagen:'ensalada.jpg',
        image:'papas con cheddarotra.png',
        image1:'papas con chedarotra.png',
        image2:'verdeo.png',
        image3:'panceta.png',
        image4:'cheddar2.png',
    },
    {
        title:"Sanguche de bondiola" ,
        stock:4  ,
        precio:800 ,
        id: 5,
        imagen:'bondiola.jpg',
        image:'papas con cheddarotra.png',
        image1:'papas con chedarotra.png',
        image2:'verdeo.png',
        image3:'panceta.png',
        image4:'cheddar2.png',
    } 
]
export default products